// Auto-generated by generateImageData.js
export interface ImageData {
  src: string;
  alt: string;
  category: string;
  description?: string;
}

export const BirthdayImages: ImageData[] = [
  {
    "src": "/images/Birthday/IMG-20231120-WA0007.jpg",
    "alt": "IMG-20231120-WA0007",
    "category": "Birthday",
    "description": "IMG-20231120-WA0007.jpg from Birthday"
  },
  {
    "src": "/images/Birthday/IMG-20231120-WA0008.jpg",
    "alt": "IMG-20231120-WA0008",
    "category": "Birthday",
    "description": "IMG-20231120-WA0008.jpg from Birthday"
  },
  {
    "src": "/images/Birthday/IMG-20231120-WA0009.jpg",
    "alt": "IMG-20231120-WA0009",
    "category": "Birthday",
    "description": "IMG-20231120-WA0009.jpg from Birthday"
  },
  {
    "src": "/images/Birthday/IMG-20231120-WA0010.jpg",
    "alt": "IMG-20231120-WA0010",
    "category": "Birthday",
    "description": "IMG-20231120-WA0010.jpg from Birthday"
  },
  {
    "src": "/images/Birthday/IMG-20241105-WA0002.jpg",
    "alt": "IMG-20241105-WA0002",
    "category": "Birthday",
    "description": "IMG-20241105-WA0002.jpg from Birthday"
  },
  {
    "src": "/images/Birthday/IMG-20241106-WA0055.jpg",
    "alt": "IMG-20241106-WA0055",
    "category": "Birthday",
    "description": "IMG-20241106-WA0055.jpg from Birthday"
  }
];

export const engagementImages: ImageData[] = [
  {
    "src": "/images/engagement/56004317f5c23936f233dfcf9d5bf1d7.jpg",
    "alt": "56004317f5c23936f233dfcf9d5bf1d7",
    "category": "engagement",
    "description": "56004317f5c23936f233dfcf9d5bf1d7.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20231202-WA0018.jpg",
    "alt": "IMG-20231202-WA0018",
    "category": "engagement",
    "description": "IMG-20231202-WA0018.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20231202-WA0027.jpg",
    "alt": "IMG-20231202-WA0027",
    "category": "engagement",
    "description": "IMG-20231202-WA0027.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20231202-WA0030.jpg",
    "alt": "IMG-20231202-WA0030",
    "category": "engagement",
    "description": "IMG-20231202-WA0030.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240105-WA0000.jpg",
    "alt": "IMG-20240105-WA0000",
    "category": "engagement",
    "description": "IMG-20240105-WA0000.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240105-WA0001.jpg",
    "alt": "IMG-20240105-WA0001",
    "category": "engagement",
    "description": "IMG-20240105-WA0001.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240105-WA0003.jpg",
    "alt": "IMG-20240105-WA0003",
    "category": "engagement",
    "description": "IMG-20240105-WA0003.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240110-WA0002.jpg",
    "alt": "IMG-20240110-WA0002",
    "category": "engagement",
    "description": "IMG-20240110-WA0002.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240110-WA0005.jpg",
    "alt": "IMG-20240110-WA0005",
    "category": "engagement",
    "description": "IMG-20240110-WA0005.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240110-WA0012.jpg",
    "alt": "IMG-20240110-WA0012",
    "category": "engagement",
    "description": "IMG-20240110-WA0012.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240110-WA0019.jpg",
    "alt": "IMG-20240110-WA0019",
    "category": "engagement",
    "description": "IMG-20240110-WA0019.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240110-WA0020.jpg",
    "alt": "IMG-20240110-WA0020",
    "category": "engagement",
    "description": "IMG-20240110-WA0020.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20240110-WA0022.jpg",
    "alt": "IMG-20240110-WA0022",
    "category": "engagement",
    "description": "IMG-20240110-WA0022.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20241205-WA0002.jpg",
    "alt": "IMG-20241205-WA0002",
    "category": "engagement",
    "description": "IMG-20241205-WA0002.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG-20241205-WA0008.jpg",
    "alt": "IMG-20241205-WA0008",
    "category": "engagement",
    "description": "IMG-20241205-WA0008.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG_20240218_192440649_AE.jpg",
    "alt": "IMG_20240218_192440649_AE",
    "category": "engagement",
    "description": "IMG_20240218_192440649_AE.jpg from engagement"
  },
  {
    "src": "/images/engagement/IMG_20240502_030900215_HDR_AE.jpg",
    "alt": "IMG_20240502_030900215_HDR_AE",
    "category": "engagement",
    "description": "IMG_20240502_030900215_HDR_AE.jpg from engagement"
  },
  {
    "src": "/images/engagement/__(1).jpg",
    "alt": "__(1)",
    "category": "engagement",
    "description": "__(1).jpg from engagement"
  },
  {
    "src": "/images/engagement/__(2).jpg",
    "alt": "__(2)",
    "category": "engagement",
    "description": "__(2).jpg from engagement"
  },
  {
    "src": "/images/engagement/__(3).jpg",
    "alt": "__(3)",
    "category": "engagement",
    "description": "__(3).jpg from engagement"
  },
  {
    "src": "/images/engagement/__(4).jpg",
    "alt": "__(4)",
    "category": "engagement",
    "description": "__(4).jpg from engagement"
  },
  {
    "src": "/images/engagement/__.jpg",
    "alt": "__",
    "category": "engagement",
    "description": "__.jpg from engagement"
  }
];

export const HaldiImages: ImageData[] = [
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2120.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2120",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2120.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2122.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2122",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2122.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2123.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2123",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2123.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2124.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2124",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2124.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2125.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2125",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2125.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2126.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2126",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2126.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2127.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2127",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2127.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2128.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2128",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2128.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2129.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2129",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2129.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2189.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2189",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2189.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2446.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2446",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2446.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2447.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2447",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2447.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2448.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2448",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2448.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2449.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2449",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2449.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2450.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2450",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2450.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2525.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2525",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2525.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2526.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2526",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2526.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2603.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2603",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2603.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2604.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2604",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2604.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2605.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2605",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2605.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2608.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2608",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2608.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2609.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2609",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2609.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2610.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2610",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2610.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2612.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2612",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2612.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2613.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2613",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2613.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2614.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2614",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2614.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2615.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2615",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2615.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2616.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2616",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2616.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2617.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2617",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2617.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2618.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2618",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2618.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2619.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2619",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2619.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2620.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2620",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2620.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2621.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2621",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2621.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2622.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2622",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2622.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2623.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2623",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2623.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2645.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2645",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2645.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2647.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2647",
    "category": "Haldi",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2647.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231121-WA0007~2.jpg",
    "alt": "IMG-20231121-WA0007~2",
    "category": "Haldi",
    "description": "IMG-20231121-WA0007~2.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231121-WA0008~2.jpg",
    "alt": "IMG-20231121-WA0008~2",
    "category": "Haldi",
    "description": "IMG-20231121-WA0008~2.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231121-WA0010.jpg",
    "alt": "IMG-20231121-WA0010",
    "category": "Haldi",
    "description": "IMG-20231121-WA0010.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231121-WA0010~2.jpg",
    "alt": "IMG-20231121-WA0010~2",
    "category": "Haldi",
    "description": "IMG-20231121-WA0010~2.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0005.jpg",
    "alt": "IMG-20231202-WA0005",
    "category": "Haldi",
    "description": "IMG-20231202-WA0005.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0006.jpg",
    "alt": "IMG-20231202-WA0006",
    "category": "Haldi",
    "description": "IMG-20231202-WA0006.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0007.jpg",
    "alt": "IMG-20231202-WA0007",
    "category": "Haldi",
    "description": "IMG-20231202-WA0007.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0008.jpg",
    "alt": "IMG-20231202-WA0008",
    "category": "Haldi",
    "description": "IMG-20231202-WA0008.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0009.jpg",
    "alt": "IMG-20231202-WA0009",
    "category": "Haldi",
    "description": "IMG-20231202-WA0009.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0010.jpg",
    "alt": "IMG-20231202-WA0010",
    "category": "Haldi",
    "description": "IMG-20231202-WA0010.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0011.jpg",
    "alt": "IMG-20231202-WA0011",
    "category": "Haldi",
    "description": "IMG-20231202-WA0011.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0012.jpg",
    "alt": "IMG-20231202-WA0012",
    "category": "Haldi",
    "description": "IMG-20231202-WA0012.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0013.jpg",
    "alt": "IMG-20231202-WA0013",
    "category": "Haldi",
    "description": "IMG-20231202-WA0013.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0014.jpg",
    "alt": "IMG-20231202-WA0014",
    "category": "Haldi",
    "description": "IMG-20231202-WA0014.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231202-WA0036.jpg",
    "alt": "IMG-20231202-WA0036",
    "category": "Haldi",
    "description": "IMG-20231202-WA0036.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/IMG-20231203-WA0038.jpg",
    "alt": "IMG-20231203-WA0038",
    "category": "Haldi",
    "description": "IMG-20231203-WA0038.jpg from Haldi"
  },
  {
    "src": "/images/Haldi/__.jpg",
    "alt": "__",
    "category": "Haldi",
    "description": "__.jpg from Haldi"
  }
];

export const MiravnukImages: ImageData[] = [
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_180.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_180",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_180.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_1877.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_1877",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_1877.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2084.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2084",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2084.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2093.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2093",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2093.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2095.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2095",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2095.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2100.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2100",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2100.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2108.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2108",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2108.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2109.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2109",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2109.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2180.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2180",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2180.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_588.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_588",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_588.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_665.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_665",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_665.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_702.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_702",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_702.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_861.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_861",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_861.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_865.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_865",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_865.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_880.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_880",
    "category": "Miravnuk",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_880.jpg from Miravnuk"
  },
  {
    "src": "/images/Miravnuk/IMG_20241003_194518930_HDR.jpg",
    "alt": "IMG_20241003_194518930_HDR",
    "category": "Miravnuk",
    "description": "IMG_20241003_194518930_HDR.jpg from Miravnuk"
  }
];

export const NaamKaranImages: ImageData[] = [
  {
    "src": "/images/Naam Karan/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_1941.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_1941",
    "category": "Naam Karan",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_1941.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2027.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2027",
    "category": "Naam Karan",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2027.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2106.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2106",
    "category": "Naam Karan",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2106.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2136.jpg",
    "alt": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2136",
    "category": "Naam Karan",
    "description": "1b874fa6-0dc3-4677-8ab3-c91f390207c1-1_all_2136.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/IMG-20241015-WA0004.jpg",
    "alt": "IMG-20241015-WA0004",
    "category": "Naam Karan",
    "description": "IMG-20241015-WA0004.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/IMG-20241015-WA0005.jpg",
    "alt": "IMG-20241015-WA0005",
    "category": "Naam Karan",
    "description": "IMG-20241015-WA0005.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/IMG-20241015-WA0006.jpg",
    "alt": "IMG-20241015-WA0006",
    "category": "Naam Karan",
    "description": "IMG-20241015-WA0006.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/IMG-20241015-WA0007.jpg",
    "alt": "IMG-20241015-WA0007",
    "category": "Naam Karan",
    "description": "IMG-20241015-WA0007.jpg from Naam Karan"
  },
  {
    "src": "/images/Naam Karan/__.jpg",
    "alt": "__",
    "category": "Naam Karan",
    "description": "__.jpg from Naam Karan"
  }
];

export const SelfiepointsImages: ImageData[] = [
  {
    "src": "/images/Selfie points/IMG_20250518_130613931_HDR_AE.jpg",
    "alt": "IMG_20250518_130613931_HDR_AE",
    "category": "Selfie points",
    "description": "IMG_20250518_130613931_HDR_AE.jpg from Selfie points"
  },
  {
    "src": "/images/Selfie points/__.jpg",
    "alt": "__",
    "category": "Selfie points",
    "description": "__.jpg from Selfie points"
  }
];

export const toranImages: ImageData[] = [
  {
    "src": "/images/toran/__(1).jpg",
    "alt": "__(1)",
    "category": "toran",
    "description": "__(1).jpg from toran"
  },
  {
    "src": "/images/toran/__(2).jpg",
    "alt": "__(2)",
    "category": "toran",
    "description": "__(2).jpg from toran"
  },
  {
    "src": "/images/toran/__(3).jpg",
    "alt": "__(3)",
    "category": "toran",
    "description": "__(3).jpg from toran"
  },
  {
    "src": "/images/toran/__(4).jpg",
    "alt": "__(4)",
    "category": "toran",
    "description": "__(4).jpg from toran"
  },
  {
    "src": "/images/toran/__(5).jpg",
    "alt": "__(5)",
    "category": "toran",
    "description": "__(5).jpg from toran"
  },
  {
    "src": "/images/toran/__(6).jpg",
    "alt": "__(6)",
    "category": "toran",
    "description": "__(6).jpg from toran"
  },
  {
    "src": "/images/toran/__(7).jpg",
    "alt": "__(7)",
    "category": "toran",
    "description": "__(7).jpg from toran"
  },
  {
    "src": "/images/toran/__(8).jpg",
    "alt": "__(8)",
    "category": "toran",
    "description": "__(8).jpg from toran"
  },
  {
    "src": "/images/toran/__.jpg",
    "alt": "__",
    "category": "toran",
    "description": "__.jpg from toran"
  }
];

export const weddingImages: ImageData[] = [
  {
    "src": "/images/wedding/IMG-20231202-WA0022.jpg",
    "alt": "IMG-20231202-WA0022",
    "category": "wedding",
    "description": "IMG-20231202-WA0022.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG-20231202-WA0025.jpg",
    "alt": "IMG-20231202-WA0025",
    "category": "wedding",
    "description": "IMG-20231202-WA0025.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG-20231202-WA0038.jpg",
    "alt": "IMG-20231202-WA0038",
    "category": "wedding",
    "description": "IMG-20231202-WA0038.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG_20231220_184554296_HDR.jpg",
    "alt": "IMG_20231220_184554296_HDR",
    "category": "wedding",
    "description": "IMG_20231220_184554296_HDR.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG_20231220_184556135_HDR.jpg",
    "alt": "IMG_20231220_184556135_HDR",
    "category": "wedding",
    "description": "IMG_20231220_184556135_HDR.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG_20240317_150119006_AE.jpg",
    "alt": "IMG_20240317_150119006_AE",
    "category": "wedding",
    "description": "IMG_20240317_150119006_AE.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG_20240421_161922012.jpg",
    "alt": "IMG_20240421_161922012",
    "category": "wedding",
    "description": "IMG_20240421_161922012.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG_20240421_161924473.jpg",
    "alt": "IMG_20240421_161924473",
    "category": "wedding",
    "description": "IMG_20240421_161924473.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG_20240502_032617191_HDR_AE.jpg",
    "alt": "IMG_20240502_032617191_HDR_AE",
    "category": "wedding",
    "description": "IMG_20240502_032617191_HDR_AE.jpg from wedding"
  },
  {
    "src": "/images/wedding/IMG_20240630_003430879_HDR_AE.jpg",
    "alt": "IMG_20240630_003430879_HDR_AE",
    "category": "wedding",
    "description": "IMG_20240630_003430879_HDR_AE.jpg from wedding"
  },
  {
    "src": "/images/wedding/__(1).jpg",
    "alt": "__(1)",
    "category": "wedding",
    "description": "__(1).jpg from wedding"
  },
  {
    "src": "/images/wedding/__(2).jpg",
    "alt": "__(2)",
    "category": "wedding",
    "description": "__(2).jpg from wedding"
  },
  {
    "src": "/images/wedding/__(3).jpg",
    "alt": "__(3)",
    "category": "wedding",
    "description": "__(3).jpg from wedding"
  },
  {
    "src": "/images/wedding/__(4).jpg",
    "alt": "__(4)",
    "category": "wedding",
    "description": "__(4).jpg from wedding"
  },
  {
    "src": "/images/wedding/__.jpg",
    "alt": "__",
    "category": "wedding",
    "description": "__.jpg from wedding"
  }
];

export const portfolioImages: ImageData[] = [
  ...BirthdayImages,
  ...engagementImages,
  ...HaldiImages,
  ...MiravnukImages,
  ...NaamKaranImages,
  ...SelfiepointsImages,
  ...toranImages,
  ...weddingImages
];

// Slideshow images (selecting best from each category)
export const slideshowImages: ImageData[] = [
  BirthdayImages[0],
  engagementImages[0],
  HaldiImages[0],
  MiravnukImages[0],
  NaamKaranImages[0],
  SelfiepointsImages[0],
  toranImages[0],
  weddingImages[0]
].filter(Boolean);

// Exclude categories globally (e.g., remove "Baby shower" everywhere)
export const EXCLUDED_CATEGORIES = new Set<string>(['Baby shower']);

export const activePortfolioImages: ImageData[] = portfolioImages.filter(img => !EXCLUDED_CATEGORIES.has(img.category));
export const activeSlideshowImages: ImageData[] = slideshowImages.filter(img => !EXCLUDED_CATEGORIES.has(img.category));

// Fallback images for when local images are not available
export const fallbackImages: ImageData[] = [
  {
    src: 'https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop',
    alt: 'Wedding Decoration',
    category: 'Wedding',
    description: 'Beautiful wedding decoration setup'
  },
  {
    src: 'https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop',
    alt: 'Birthday Party',
    category: 'Birthday',
    description: 'Colorful birthday party decoration'
  },
  {
    src: 'https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop',
    alt: 'Engagement Ceremony',
    category: 'Engagement',
    description: 'Elegant engagement ceremony setup'
  }
];

export const fallbackSlideshowImages: ImageData[] = [
  {
    src: 'https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
    alt: 'Wedding Decoration',
    category: 'Wedding',
    description: 'Stunning wedding decoration with traditional elements and modern aesthetics'
  },
  {
    src: 'https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
    alt: 'Birthday Celebration',
    category: 'Birthday',
    description: 'Vibrant birthday party decoration with balloons and colorful themes'
  },
  {
    src: 'https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg?auto=compress&cs=tinysrgb&w=1200&h=600&fit=crop',
    alt: 'Engagement Setup',
    category: 'Engagement',
    description: 'Elegant engagement ceremony decoration with floral arrangements'
  }
];

// Get all unique categories
export const getAllCategories = (): string[] => {
  const categories = new Set(activePortfolioImages.map(img => img.category));
  return Array.from(categories).sort();
};

// Get categories sorted by image count (most images first)
export const getCategoriesByCount = () => {
  const categoryCounts = activePortfolioImages.reduce((acc, img) => {
    acc[img.category] = (acc[img.category] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return Object.entries(categoryCounts)
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count); // Sort by count descending
};
